/**
 * This file was generated by the JPA Modeler
 */
package tn.esprit.sigma.witnessbook.entities;

import java.io.Serializable;
import javax.persistence.Entity;

/**
 * @author omarm
 */
@Entity
public class Moderator extends Users implements Serializable {
	private static final long serialVersionUID = 1L;

}
